# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lebana/Documents/CompGraf/-CG-2020-I-Computacion-Grafica

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lebana/Documents/CompGraf/-CG-2020-I-Computacion-Grafica

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lebana/Documents/CompGraf/-CG-2020-I-Computacion-Grafica/CMakeFiles /home/lebana/Documents/CompGraf/-CG-2020-I-Computacion-Grafica/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lebana/Documents/CompGraf/-CG-2020-I-Computacion-Grafica/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f dependences/glfw-3.3.2/src/CMakeFiles/glfw.dir/build.make dependences/glfw-3.3.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

dependences/glad/src/glad.o: dependences/glad/src/glad.c.o

.PHONY : dependences/glad/src/glad.o

# target to build an object file
dependences/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/dependences/glad/src/glad.c.o
.PHONY : dependences/glad/src/glad.c.o

dependences/glad/src/glad.i: dependences/glad/src/glad.c.i

.PHONY : dependences/glad/src/glad.i

# target to preprocess a source file
dependences/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/dependences/glad/src/glad.c.i
.PHONY : dependences/glad/src/glad.c.i

dependences/glad/src/glad.s: dependences/glad/src/glad.c.s

.PHONY : dependences/glad/src/glad.s

# target to generate assembly for a file
dependences/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/dependences/glad/src/glad.c.s
.PHONY : dependences/glad/src/glad.c.s

src/Exercises/key_color_triangle.o: src/Exercises/key_color_triangle.cpp.o

.PHONY : src/Exercises/key_color_triangle.o

# target to build an object file
src/Exercises/key_color_triangle.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Exercises/key_color_triangle.cpp.o
.PHONY : src/Exercises/key_color_triangle.cpp.o

src/Exercises/key_color_triangle.i: src/Exercises/key_color_triangle.cpp.i

.PHONY : src/Exercises/key_color_triangle.i

# target to preprocess a source file
src/Exercises/key_color_triangle.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Exercises/key_color_triangle.cpp.i
.PHONY : src/Exercises/key_color_triangle.cpp.i

src/Exercises/key_color_triangle.s: src/Exercises/key_color_triangle.cpp.s

.PHONY : src/Exercises/key_color_triangle.s

# target to generate assembly for a file
src/Exercises/key_color_triangle.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Exercises/key_color_triangle.cpp.s
.PHONY : src/Exercises/key_color_triangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... glad"
	@echo "... glfw"
	@echo "... dependences/glad/src/glad.o"
	@echo "... dependences/glad/src/glad.i"
	@echo "... dependences/glad/src/glad.s"
	@echo "... src/Exercises/key_color_triangle.o"
	@echo "... src/Exercises/key_color_triangle.i"
	@echo "... src/Exercises/key_color_triangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

